name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install package dependencies
        run: flutter pub get

      - name: Analyze package
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Analyze example
        run: |
          cd example
          flutter pub get
          flutter analyze